export interface FCBKLossMitDisplayEntity {
    bankruptcyCategory: string
    methodOfForeclosure: string
    foreclosureStepCode: any
    foreclosureStepCodeDescription: any
    foreclosureStepActualCompletionDateString: any
    foreclosureStepScheduledCompletionDateString: any
    foreclosureStepCostString: any
    actualFCLDateString: string
    foreclosureStatus: string
    serviceCompletedString: string
    judgementEnteredString: string
    refToAttnyString: string
    estimatedFCLDateString: string
    c1stLegalString: string
    state: string
    loanID: any
    servicingLoanNum: any
    daysInFC: any
    daysInFCString: any
    actualSaleScheduledDate: any
    actualSaleScheduledDateString: any
    actualForeclosureDate: any
    actualForeclosureDateString: any
    actualJudgementEntedDate: any
    actualJudgementEntedDateString: any
    serviceCompletedActualDate: any
    serviceCompletedActualDateString: any
    firstLeaglCompletionActualDate: any
    firstLeaglCompletionActualDateString: any
    referredtoAttorneyActualDate: any
    referredtoAttorneyActualDateString: any
    foreclosureLatestStepCompleted: any
    scheduleSaleScheduleDate: any
    scheduleSaleScheduleDateString: any
    bkStatus: string
    bkCaseNumber: string
    bkFilingDate: any
    bkFilingDateString: string
    bkDischargeDate: any
    bkDischargeDateString: string
    lastPaymentDueDate: any
    lastPaymentDueDateString: string
    postPetitionDueDate: any
    postPetitionDueDateString: string
    pocRefferedtoAttorneyActualDate: any
    pocRefferedtoAttorneyActualDateString: string
    pocFiledwithCourtActualDate: any
    pocFiledwithCourtActualDateString: string
    bkPlanConfActualDate: any
    bankruptcyPlanConfActualDateString: string
    confHearingActualDate: any
    confHearingActualDateString: string
    mfrReferredtoAttorneyActualDate: any
    mfrReferredtoAttorneyActualDateString: string
    hearingActualDate: any
    hearingActualDateString: string
    mfrGrantedActualDate: any
    mfrGrantedActualDateString: string
    lmAccountingDate: any
    lmAccountingDateString: any
    lmDecision: any
    denialReasonAndDescription: any
    lmApprovalDate: any
    lmApprovalDateString: any
    lmDecisionBuckets: any
    lmTemplate: any
    lmStatus: string
    lossMitStartDateString: string
    lossMitDenialDateString: string
    lossMitCurrentMilestoneString: string
    lossMitDealTypeString: string
    lossMitClosedDateString: string
    lossMitApprovalDateString: string
  }
  